### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by abubelinha** [JordyHers/Times-up-flutter#247]
**Is your feature request related to a problem? Please describe.**
I can't figure out how to install this in my phone or my child's phone

**Describe the solution you'd like**
Some instructions added to README 
or a link to instructions if they already exist, 
or a link to the store app, or whatever is needed to install this

**Describe alternatives you've considered**
Asked in [discussions](https://github.com/orgs/JordyHers-org/discussions/246).

**Comment by JordyHers** [comment]
@abubelinha APK file added to readme you can download install and have a look. As the apk is not signed login with Google may fail. Please try signing up with Email
